### PR TITLE
upd(button): update button font + states for redesign

### PR DESCRIPTION
**Pull request by jayjayjpg**
Part of https://github.com/meroxa/mx-ui-components/issues/36
Also part of https://github.com/meroxa/platform-ui-v1/issues/283

### CODE REVIEW

**Review by raulb — COMMENTED** [review]
@jayjayjpg are these in use anywhere so I can look at the differences visually?

**Comment by jayjayjpg** [comment]
@raulb Yes sure, you can check out the affected button elements over at the work in progress PR here: https://github.com/meroxa/mx-ui-components/pull/49

A link to a demo site (via Chromatic) and screenshots are available in the PR description!

**Review by raulb — APPROVED** [review]
@jayjayjpg thank you for the demo! LGTM

**Comment by jayjayjpg** [comment]
@raulb Thank you for the swift review! 🙇🏾‍♀️

**Pull request merged**
