### PR TITLE
fix(colors): improve a11y by increasing red contrast

### PR DESCRIPTION
**Pull request by jayjayjpg**
While working on https://github.com/meroxa/mx-ui-components/pull/21 our accessibility checks failed because [the color contrast for red elements was too low](https://github.com/meroxa/mx-ui-components/pull/21#discussion_r680957226).

According to WCAG 2.x, the color contrast between background and foreground colors needs to be at least 7.3:1 to meet the AAA level success criterion for color accessibility. You can learn more about WCAG success criteria for color contrast and why it matters for accessibility [here](https://www.notion.so/meroxa/WCAG-Compliant-Color-Palette-4ccb4cab915f453e81870f2268eadcf4)

This darkens the red tone `saffron-100` used for our button elements to be WCAG compliant when used in combination with white text.

Closes https://github.com/meroxa/product/issues/92

| before | after |
|--|--|
| `#DE583E` | `#DC2626` |

### CODE REVIEW

**Comment by brettgoulder** [comment]
Actually, we might have too much contrast here. I think WCAG AA should be sufficeint for colors.

What about something like #D64224 to get a 4.5:1 contrast ratio?

Screen Shot 2021-08-04 at 11 29 40 AM

**Comment by jayjayjpg** [comment]
@brettgoulder Good catch! 

@justmisosoup and @ogeyejammy made a good point, that we could also aim for the AAA level success criterion if we wanted to update this color, which would require a 7.3:1 ratio at minimum for elements with normal and small font-sizes. I agree that aiming for the highest success criterion would be ideal

A review of our color palette is in progress and I can update this PR accordingly a decision has been made

**Comment by brettgoulder** [comment]
[According to the W3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html#uc-conf-req1-head
) states "It is not recommended that Level AAA conformance be required as a general policy for entire sites because it is not possible to satisfy all Level AAA Success Criteria for some content." 

I think it would be good to come to an understanding of what accessability criteria we are trying to shoot for.

**Comment by jayjayjpg** [comment]
@brettgoulder @Sara @justmisosoup Do we have consensus on the shade we could use for danger elements for now? I think we could also reiterate on the color in the future when the entire palette is updated

What are your thoughts?

**Comment by ogeyejammy** [comment]
No real decisions have been made regarding the color palette yet. I'm still
playing with a few options surrounding the shades and rules. I want to make
this as intentional as possible.

Kindly,
Lee Dante Guarin
--
***@***.***
(925) 336-3336

http://www.meroxa.io
Empower your data team.

**Comment by jayjayjpg** [comment]
@ogeyejammy Thank you, that sounds good!

**Review by brettgoulder — APPROVED** [review]
💯

**Comment by jayjayjpg** [comment]
Thank you! 🙇🏾‍♀️

**Pull request merged**
